### ISSUE TITLE
tabs -> spaces

### ISSUE THREAD

**Issue by nschloe** [TheAppliedMathematician/BlockLinAlg#2]
Using tabs is not recommended since it renders differently on different machines (and for some other reasons). Spaces are nowadays the white space of choice. :) I'd recommend sticking to that.

**Comment by TheAppliedMathematician** [comment]
Sorry for the novice query, but we shall still retain the indentation as 4 space characters, right?

**Comment by nschloe** [comment]
Indeed. Always stick to [PEP8](https://www.python.org/dev/peps/pep-0008/#indentation) if possible.

**Comment by TheAppliedMathematician** [comment]
The change has been pushed. Thanks!
